
trigger:
  branches:
    include:
    - master
pr:
- master

resources:
- repo: self

variables:
  id: '$(Build.BuildId)'

stages:
- stage: Check Pull Request
  displayName: Build image for PR
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: Build
    displayName: Build image for PR
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: sudo docker login
      displayName: Login to Docker Hub
    - script: sudo docker pull homeassistant/amd64-builder
      displayName: Install hassio builder
    - script: |
        docker run --rm --privileged -v ~/.docker:/root/.docker \
        -v /zigbee2mqtt:/data homeassistant/amd64-builder --all -t /data --test
      displayName: Build zigbee2mqtt with tag :test (no push)
    - script: |
        docker run --rm --privileged -v ~/.docker:/root/.docker \
        -v /zigbee2mqtt-edge:/data homeassistant/amd64-builder --all -t /data --test
      displayName: Build zigbee2mqtt-edge with tag :test (no push)


- stage: Build and Push
  displayName: Build images and push to Docker Hub
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: build_and_push_test
    displayName: Build and Push non-release
    pool:
      vmImage: 'ubuntu-latest'
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    steps:
    - script: sudo docker login
      displayName: Login to Docker Hub
    - script: sudo docker pull homeassistant/amd64-builder
      displayName: Install hassio builder
    # untagged push to master -> build and push images with :test
    - script: |
        docker run --rm --privileged -v ~/.docker:/root/.docker \
        -v /zigbee2mqtt:/data homeassistant/amd64-builder --all -t /data \
        --version test --no-latest
      displayName: Build zigbee2mqtt with tag :test
    - script: |
        docker run --rm --privileged -v ~/.docker:/root/.docker \
        -v /zigbee2mqtt-edge:/data homeassistant/amd64-builder --all -t /data \
        --version test --no-latest
      displayName: Build zigbee2mqtt-edge with tag :test

  - job: build_and_push_release
    displayName: Build and Push release
    pool:
      vmImage: 'ubuntu-latest'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    steps:
    # check to make sure tag version matches json config
    # - script: |
    #     SOURCE='$(Build.SourceBranch)'
    #     TAG="${SOURCE/refs\/tags\//}"
    #     CONFIG_VER="$(jq -r '.version' ./zigbee2mqtt/config.json)"
    #     if ["${TAG//v}" = "$CONFIG_VER"]; then
    #       exit 0
    #     else
    #       echo "git tag $TAG does not match config.json version" && exit 1
    #     fi
    # tagged push to master -> build and push images with tag :latest and :git_tag
    # - script: |
    #     docker run --rm --privileged -v ~/.docker:/root/.docker \
    #     -v ./zigbee2mqtt:/data homeassistant/amd64-builder --all -t /data \
    #     --version "$CONFIG_VER"
    #   condition: succeeded()